// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlOD5xrNYsrJnik0lFt4pkUcHY_3-QwbY',
    appId: '1:83226244081:web:2cdb2f105a6a391c3d8a50',
    messagingSenderId: '83226244081',
    projectId: 'chatappflutter-2b3d6',
    authDomain: 'chatappflutter-2b3d6.firebaseapp.com',
    storageBucket: 'chatappflutter-2b3d6.appspot.com',
    measurementId: 'G-B4W3YVXKFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFd5Kt7hZsoLvoFCxH7J48A2qHVsPM73Y',
    appId: '1:83226244081:android:a2aa1320c4e185cf3d8a50',
    messagingSenderId: '83226244081',
    projectId: 'chatappflutter-2b3d6',
    storageBucket: 'chatappflutter-2b3d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgurXsTrQqnh0TgAnZK5s0MaJ6qx5u8Sw',
    appId: '1:83226244081:ios:9f29ac589c42fb773d8a50',
    messagingSenderId: '83226244081',
    projectId: 'chatappflutter-2b3d6',
    storageBucket: 'chatappflutter-2b3d6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgurXsTrQqnh0TgAnZK5s0MaJ6qx5u8Sw',
    appId: '1:83226244081:ios:2b470f02b8506f003d8a50',
    messagingSenderId: '83226244081',
    projectId: 'chatappflutter-2b3d6',
    storageBucket: 'chatappflutter-2b3d6.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
